[2024-07-11T15:29:45.324+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-11T15:29:45.364+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_notebook_dag.run_notebook manual__2024-07-11T08:28:16.118647+00:00 [queued]>
[2024-07-11T15:29:45.384+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_notebook_dag.run_notebook manual__2024-07-11T08:28:16.118647+00:00 [queued]>
[2024-07-11T15:29:45.386+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-11T15:29:45.458+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_notebook> on 2024-07-11 08:28:16.118647+00:00
[2024-07-11T15:29:45.465+0700] {standard_task_runner.py:63} INFO - Started process 47217 to run task
[2024-07-11T15:29:45.469+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'run_notebook_dag', 'run_notebook', 'manual__2024-07-11T08:28:16.118647+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/run_notebook.py', '--cfg-path', '/tmp/tmpe732vctl']
[2024-07-11T15:29:45.473+0700] {standard_task_runner.py:91} INFO - Job 12: Subtask run_notebook
[2024-07-11T15:29:45.679+0700] {task_command.py:426} INFO - Running <TaskInstance: run_notebook_dag.run_notebook manual__2024-07-11T08:28:16.118647+00:00 [running]> on host LWIN-ID-OCT22-0115.
[2024-07-11T15:29:45.947+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='lk' AIRFLOW_CTX_DAG_ID='run_notebook_dag' AIRFLOW_CTX_TASK_ID='run_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T08:28:16.118647+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-11T08:28:16.118647+00:00'
[2024-07-11T15:29:45.950+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-11T15:29:45.952+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-11T15:29:45.954+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/dags/run_notebook.py", line 14, in run_notebook
    pm.execute_notebook(
TypeError: execute_notebook() missing 1 required positional argument: 'output_path'
[2024-07-11T15:29:45.994+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=run_notebook_dag, task_id=run_notebook, run_id=manual__2024-07-11T08:28:16.118647+00:00, execution_date=20240711T082816, start_date=20240711T082945, end_date=20240711T082945
[2024-07-11T15:29:46.058+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task run_notebook (execute_notebook() missing 1 required positional argument: 'output_path'; 47217)
[2024-07-11T15:29:46.087+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-11T15:29:46.129+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-11T15:29:46.135+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
