[2024-07-11T23:36:14.907+0700] {scheduler_job_runner.py:843} ERROR - Executor reports task instance <TaskInstance: update_allogistic_dag.execute_ipnb scheduled__2024-07-11T15:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
